name: CI/CD for wisecow

on:
 push:
  branches:
   - main
 pull_request:

jobs:
 build-and-deploy:
  runs-on: self-hosted
  steps:
# code checkout
   - name: Checkout the code
     uses: actions/checkout@v3
# log in to dockerhub
   - name: docker login
     uses: docker/login-action@v2
     with:
      username: ${{secrets.username}}
      password: ${{secrets.password}}
  # docker build and push the image to dockerhub registory
   - name: Build and Push Docker image
     run: |
          IMAGE=${{secrets.username}}/wisecow:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .
          docker push $IMAGE
          docker rmi $IMAGE
     # delete local docker image 
  # - name: Remove local Docker image
  #   run: docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/wisecow:latest || true
 # intialise the deployment in local k8s 
   - name: Update deployment image
     run: |
       kubectl set image deployment/wisecow-deployment wisecow-cont=${{secrets.username}}/wisecow:${{ github.sha }} -n accuknox
       kubectl rollout status deployment/wisecow-deployment -n accuknox

   
